{-
Author: Nick(Mykola) Pershyn
Language: Haskell
Program: Dominion Client
-}

module DominionNotifications where

my_not1 = "(move ((players 0-player-v1 1-player-v1) (supply copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold estate estate estate estate estate estate estate estate duchy duchy duchy duchy duchy duchy duchy duchy province province province province province province province province mine mine mine mine mine mine mine mine mine mine) (trash) (actions 1) (buys 1) (coins 0) (deck copper copper copper copper estate) (hand estate copper estate copper copper) (plays) (discards)))\n"

myNotWithSpaces = "  (  move  (  (  players  0-player-v1   1-player-v1  )   (  supply   copper   copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper   copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper  copper copper copper copper copper copper copper copper copper copper copper copper copper copper copper silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver silver gold gold gold gold gold gold gold    gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold gold estate estate estate estate estate estate estate     estate duchy   duchy duchy duchy duchy duchy duchy duchy province province province province province province province province    mine mine   mine mine mine mine mine mine mine   mine   )   (     trash )   (  actions   1  )   (  buys   1 )   ( coins    0  )   ( deck    copper    copper copper copper   estate  )   (  hand   estate    copper  estate   copper   copper   )    (   plays   )    (  discards   )   )   )  \n"
